### PR TITLE
Use spec compliant names for devices and data to fix issue #93.

### LINKED ISSUE #93: Use names for sim CAN devices and data that conform to spec
Based on my reading of [the spec](https://github.com/wpilibsuite/allwpilib/blob/main/simulation/halsim_ws_core/doc/hardware_ws_api.md), we should make the following changes:

1. SparkMax[id] -> CANMotor:CANSparkMax[id] with Speed -> percentOutput and Current Draw -> motorCurrent
3. SparkFlex[id] -> CANMotor:CANSparkMax[id] with Speed -> percentOutput and Current Draw -> motorCurrent
4. Spark*[id]_RelativeEncoder -> CANEncoder:CANSpark*[id] with Position -> position (w/ units changed to rotations) and Velocity -> velocity (w/ units changed to rps)
5. Spark*[id]_AbsoluteEncoder -> CANDutyCycle:CANSpark*[id] with Position -> position (w/ units changed to rotations)
6. CANCoder[i] -> CANDutyCycle:CANCoder[id] with count -> position (w/ units changed to rotations)
7. (maybe?) PlayingWithFusionTimeOfFlight[i] -> CANAIn:PlayingWithFusionTimeOfFlight[i]-rangeVoltsIsMM with range->voltage and CANAIn:PlayingWithFusionTimeOfFlight[i]-ambientLightLevelVoltsIsMcps with ambientLightLevel->voltage.
8. Change other data names to camel case for consistency (e.g. "Neutral Deadband" -> neutralDeadband).

Thoughts @CoolSpy3?

I would especially like to get the units changed so that simulation code don't need to [jump through hoops](https://github.com/DeepBlueRobotics/RobotCode2024/blob/68bf4fc48e021a23864db119b056bfcf85cd9445/src/main/java/org/carlmontrobotics/subsystems/Arm.java#L471-L473) to undo the various calculations that lib199 then redoes.

### PR DESCRIPTION
**Pull request by brettle**
fix #93

### CODE REVIEW

File: src/main/java/org/carlmontrobotics/lib199/sim/MockedCANCoder.java [hunk 1]
```diff
@@ -16,31 +15,31 @@
...
+        deviceSim = new SimDeviceSim("CANDutyCycle:CANCoder", port);
         deviceSim.registerValueChangedCallback(position, new SimValueCallback() {
             @Override
             public void callback(String name, int handle, int direction, HALValue value) {
-                sim.setRawPosition(value.getDouble() / kCANCoderCPR);
+                sim.setRawPosition(value.getDouble());
             }
         }, true);
         sims.put(port, this);
+        init = device.createBoolean("init", Direction.kOutput, true);
```
Comment (CoolSpy3) [inline src/main/java/org/carlmontrobotics/lib199/sim/MockedCANCoder.java:42]: `CANDutyCycle` does not have an `"init"` value. It does have a `"connected"` value, but that's an input rather than an output.

File: src/main/java/org/carlmontrobotics/lib199/sim/MockedEncoder.java [hunk 2]
```diff
@@ -37,17 +39,24 @@ public class MockedEncoder implements AbsoluteEncoder, AnalogInput, AutoCloseabl
...
+        position = device.createDouble("position", Direction.kInput, 0); // Rotations
+        velocity = device.createDouble("velocity", Direction.kInput, 0); // Rotations per *second*
+        if (analog) {
+            voltage = device.createDouble("voltage", Direction.kInput, 0);
+        } else {
+            voltage = null;
+        }
+        this.countsPerRev = countsPerRev;
         this.absolute = absolute;
+        init = device.createBoolean("init", Direction.kOutput, true);
```
Comment (CoolSpy3) [inline src/main/java/org/carlmontrobotics/lib199/sim/MockedEncoder.java:59]: Because this value is only used for `CANAIn` devices, it could be gated behind the above `analog` check. Although, given that we are allowed to transmit additional data values, it might just add more complexity without much benefit (given we'd also need an additional check in `close()`).

File: src/main/java/org/carlmontrobotics/lib199/sim/MockedEncoder.java [hunk 3]
```diff
@@ -95,7 +105,7 @@ public double getPosition() {
 
     @Override
     public double getVelocity() {
-        return velocity.get() * (inverted ? -1 : 1) * velocityConversionFactor / countsOrVoltsPerRev;
```
Comment (CoolSpy3) [inline src/main/java/org/carlmontrobotics/lib199/sim/MockedEncoder.java:98]: I just noticed that there needs to be a difference in implementations here. `AbsoluteEncoder` returns velocities in rps, and `RelativeEncoder` uses rpm.

Also note that `velocity` does not exist for `CANDutyCycle` objects. We could transmit it as an additional value, but as of DeepBlueRobotics/WPIWebSockets#34, that functionality is no longer directly exposed.

File: src/main/java/org/carlmontrobotics/lib199/sim/MockedMotorBase.java [hunk 4]
```diff
@@ -42,12 +43,13 @@ public abstract class MockedMotorBase implements AutoCloseable, MotorController,
...
         this.port = port;
-        speed = device.createDouble("Speed", Direction.kOutput, 0.0);
-        neutralDeadband = device.createDouble("Neutral Deadband", Direction.kOutput, 0.04);
-        brakeModeEnabled = device.createBoolean("Brake Mode", Direction.kOutput, true);
-        currentDraw = device.createDouble("Current Draw", Direction.kInput, 0.0);
+        speed = device.createDouble("percentOutput", Direction.kOutput, 0.0);
+        neutralDeadband = device.createDouble("neutralDeadband", Direction.kOutput, 0.04);
+        brakeModeEnabled = device.createBoolean("brakeMode", Direction.kOutput, true);
+        currentDraw = device.createDouble("motorCurrent", Direction.kInput, 0.0);
+        init = device.createBoolean("init", Direction.kOutput, true);
```
Comment (CoolSpy3) [inline src/main/java/org/carlmontrobotics/lib199/sim/MockedMotorBase.java:52]: `CANMotor` does not have an `"init"` value.

Additionally, we should add support for `"busVoltage"` and use it to replace `defaultNominalVoltage`.

File: src/main/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlight.java [hunk 5]
```diff
@@ -17,33 +18,39 @@
...
     private SimEnum status;
     private SimEnum rangingMode;
 
     public MockedPlayingWithFusionTimeOfFlight(int portNumber) {
         port = portNumber;
-        device = SimDevice.create("PlayingWithFusionTimeOfFlight", port);
-        range = device.createDouble("range", Direction.kInput, 0);
-        rangeSigma = device.createDouble("rangeSigma", Direction.kInput, 1);
-        sampleTime = device.createDouble("sampleTime", Direction.kBidir, 24);
+        rangeDevice = SimDevice.create("CANAIn:PlayingWithFusionTimeOfFlight[%d]-rangeVoltsIsMM".formatted(port));
```
Comment (CoolSpy3) [inline src/main/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlight.java:31]: Off-topic, but do you think it would be worth opening a pr to add a `SimDeviceSim.create(String, int, String)` method to support this device name format?

File: src/main/java/org/carlmontrobotics/lib199/swerve/SwerveModuleSim.java [hunk 6]
```diff
@@ -36,14 +36,14 @@ public class SwerveModuleSim {
...
         this.driveGearing = driveGearing;
         this.driveInversion = driveInversion;
 
-        turnMotorSim = new SimDeviceSim("SparkMax", turnMotorPortNum);
-        turnEncoderSim = new SimDeviceSim("CANCoder", turnEncoderPortNum);
+        turnMotorSim = new SimDeviceSim("CANMotor:CANSparkMax", turnMotorPortNum);
+        turnEncoderSim = new SimDeviceSim("CANDutyCycle:CANCoder", turnEncoderPortNum);
         turnPhysicsSim = new DCMotorSim(DCMotor.getNEO(1), turnGearing, turnMoiKgM2);
         this.turnGearing = turnGearing;
         this.turnInversion = turnInversion;
```
Comment (CoolSpy3) [inline src/main/java/org/carlmontrobotics/lib199/swerve/SwerveModuleSim.java:49]: It looks like `driveInversion`, `turnGearing`, and `turnInversion` are unused. Is this intentional?

File: src/test/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlightTest.java [hunk 7]
```diff
@@ -164,13 +164,14 @@ private void withDevices(EncoderTest func) {
 
     private void withDevice(int id, EncoderTest func) {
         try(TimeOfFlight dev = createDevice(id)) {
-            SimDeviceSim sim = new SimDeviceSim("PlayingWithFusionTimeOfFlight", id);
-            func.test((TimeOfFlight)dev, sim);
+            SimDeviceSim rangeDeviceSim = new SimDeviceSim(String.format("CANAIn:PlayingWithFusionTimeOfFlight[%d]-rangeVoltsIsMM", id));
+            SimDeviceSim ambientLightLevelDeviceSim = new SimDeviceSim(String.format("CANAIn:PlayingWithFusionTimeOfFlight[%d]-ambientLightLevelVoltsIsMcps", id));
+            func.test((TimeOfFlight)dev, rangeDeviceSim, ambientLightLevelDeviceSim);
```
Comment (CoolSpy3) [inline src/test/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlightTest.java:169]: Unnecessary cast to `TimeOfFlight`.

File: src/test/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlightTest.java [hunk 8]
```diff
@@ -164,13 +164,14 @@ private void withDevices(EncoderTest func) {
...
         }
     }
 
     private interface EncoderTest {
-        public void test(TimeOfFlight encoder, SimDeviceSim sim);
+        public void test(TimeOfFlight encoder, SimDeviceSim rangeDeviceSim, SimDeviceSim ambientLightLevelDeviceSim);
     }
```
Comment (CoolSpy3) [inline src/test/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlightTest.java:175]: `EncoderTest` and `encoder` should probably be renamed.

**Review by CoolSpy3 — CHANGES_REQUESTED** [review]

File: src/main/java/org/carlmontrobotics/lib199/sim/MockedCANCoder.java [hunk 9]
```diff
@@ -16,31 +15,31 @@
...
     private SimDouble position; // Rotations - Continuous
     private SimDouble gearing;
+    private SimBoolean init;
     private CANcoderSimState sim;
 
     public MockedCANCoder(CANcoder canCoder) {
         port = canCoder.getDeviceID();
-        device = SimDevice.create("CANCoder", port);
-        position = device.createDouble("count", Direction.kInput, 0);
+        device = SimDevice.create("CANDutyCycle:CANCoder", port);
```
[the remark this answers is not in the document]
Comment (brettle) [reply src/main/java/org/carlmontrobotics/lib199/sim/MockedCANCoder.java:30]: Would prefer to handle in a separate PR if it is needed.

File: src/main/java/org/carlmontrobotics/lib199/sim/MockedEncoder.java (hunk 2 above)
Comment (brettle) [reply src/main/java/org/carlmontrobotics/lib199/sim/MockedEncoder.java:59]: Inclined to leave it for simplicity.

File: src/main/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlight.java (hunk 5 above)
Comment (brettle) [reply src/main/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlight.java:31]: No objections, but not a high priority either.

File: src/main/java/org/carlmontrobotics/lib199/swerve/SwerveModuleSim.java (hunk 6 above)
Comment (brettle) [reply src/main/java/org/carlmontrobotics/lib199/swerve/SwerveModuleSim.java:49]: `driveInversion` and `turnInversion` are not needed here because they should be set correctly on the respective motors.
The `turnGearing` passed to the constructor is used to create an accurate sim of the turn physics (`turnPhysicsSim`), but is not used outside the constructor. I'm removing the other references.

File: src/main/java/org/carlmontrobotics/lib199/sim/MockedEncoder.java (hunk 3 above)
Comment (brettle) [reply src/main/java/org/carlmontrobotics/lib199/sim/MockedEncoder.java:98]: For now, I'm going to address the different units with an anonymous subclass that overrides `getVelocity()` when we create an absolute encoder.

Also for now I'm ok with velocity not working with DeepBlueSim/WPIWebSockets. At least this way it can work with other simulators.

File: src/main/java/org/carlmontrobotics/lib199/sim/MockSparkBase.java [hunk 10]
```diff
@@ -44,14 +45,15 @@ public class MockSparkBase extends MockedMotorBase {
...
      */
-    public MockSparkBase(int port, MotorType type, String name) {
+    public MockSparkBase(int port, MotorType type, String name, int countsPerRev) {
         super(name, port);
         this.type = type;
+        this.name = name;
 
         if(type == MotorType.kBrushless) {
-            encoder = new MockedEncoder(SimDevice.create(device.getName() + "_RelativeEncoder"), MockedEncoder.NEO_BUILTIN_ENCODER_CPR, false) {
+            encoder = new MockedEncoder(SimDevice.create("CANEncoder:%s[%d]".formatted(name, port)), countsPerRev, false, false) {
```
[the remark this answers is not in the document]
Comment (brettle) [reply src/main/java/org/carlmontrobotics/lib199/sim/MockSparkBase.java]: Now fixed.

File: src/main/java/org/carlmontrobotics/lib199/sim/MockSparkBase.java [hunk 11]
```diff
@@ -44,14 +45,15 @@ public class MockSparkBase extends MockedMotorBase {
      * @param port the port to associate this {@code MockSparkMax} with. Will be used to create the {@link SimDevice} and facilitate motor following.
      * @param type the type of the simulated motor. If this is set to {@link MotorType#kBrushless}, the builtin encoder simulation will be configured
      * to follow the inversion state of the motor and its {@code setInverted} method will be disabled.
-     * @param name the name of the type of controller ("SparkMax" or "SparkFlex")
+     * @param name the name of the type of controller ("CANSparkMax" or "CANSparkFlex")
      */
-    public MockSparkBase(int port, MotorType type, String name) {
+    public MockSparkBase(int port, MotorType type, String name, int countsPerRev) {
```
[the remark this answers is not in the document]
Comment (brettle) [reply src/main/java/org/carlmontrobotics/lib199/sim/MockSparkBase.java:51]: Now fixed.

File: src/main/java/org/carlmontrobotics/lib199/sim/MockedCANCoder.java [hunk 12]
```diff
@@ -16,31 +15,31 @@
...
+        position = device.createDouble("position", Direction.kInput, 0);
         gearing = device.createDouble("gearing", Direction.kOutput, 1);
```
[the remark this answers is not in the document]
Comment (brettle) [reply src/main/java/org/carlmontrobotics/lib199/sim/MockedCANCoder.java]: Now fixed.

File: src/main/java/org/carlmontrobotics/lib199/sim/MockedCANCoder.java (hunk 1 above)
Comment (brettle) [reply src/main/java/org/carlmontrobotics/lib199/sim/MockedCANCoder.java]: Now fixed.

File: src/main/java/org/carlmontrobotics/lib199/sim/MockedMotorBase.java (hunk 4 above)
Comment (brettle) [reply src/main/java/org/carlmontrobotics/lib199/sim/MockedMotorBase.java]: Now fixed.

File: src/test/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlightTest.java (hunk 7 above)
Comment (brettle) [reply src/test/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlightTest.java]: Now fixed.

File: src/test/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlightTest.java (hunk 8 above)
Comment (brettle) [reply src/test/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlightTest.java]: Now fixed.

**Review by CoolSpy3 — APPROVED** [review]
